### ISSUE TITLE
Data doesn't show in event page

### ISSUE THREAD

**Issue by PunyaweeSrithongkerd** [PunyaweeSrithongkerd/KU-Event-Regis#8]
![image](https://user-images.githubusercontent.com/48820372/69314546-01d32100-0c67-11ea-8728-d52caf773fad.png)
It won't show any event data from my database but for the regis page
![image](https://user-images.githubusercontent.com/48820372/69314645-4068db80-0c67-11ea-8c59-b32017911e00.png)
Is you computure have same problem too Gunn?

**Comment by gunnkrub** [comment]
No, I dont have this problem. Did u just pull master or not?

**Comment by PunyaweeSrithongkerd** [comment]
Bad new: I run in master and it already up to date.

**Comment by PunyaweeSrithongkerd** [comment]
Can you sent an screenshot from you computer?

**Comment by gunnkrub** [comment]
Event in index page show only upcoming event. Event in the past will not exist.

**Comment by PunyaweeSrithongkerd** [comment]
Problem solve closing the issue
